version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - uploaded_files:/app/uploads
      - ./instance:/app/instance
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - UPLOAD_FOLDER=/app/uploads
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - uploaded_files:/app/uploads
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  uploaded_files:

networks:
  app_network:
    driver: bridge 