"""Update models for anonymous submissions

Revision ID: 197463a574a9
Revises: 07c6e57eae33
Create Date: 2025-05-12 15:58:44.649680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '197463a574a9'
down_revision = '07c6e57eae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitter_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('submitter_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_minutes', sa.Integer(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('printer',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('material',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('rejection_reasons',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('thumbnail_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('weight_g')
        batch_op.drop_column('time_min')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_min', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('weight_g', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.alter_column('thumbnail_path',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('rejection_reasons',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('material',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('printer',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('time_minutes')
        batch_op.drop_column('time_hours')
        batch_op.drop_column('weight')
        batch_op.drop_column('submitter_email')
        batch_op.drop_column('submitter_name')

    # ### end Alembic commands ###
