"""Remove password fields from User model

Revision ID: 321fd5034294
Revises: 786928990d2f
Create Date: 2025-05-12 15:51:44.276695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321fd5034294'
down_revision = '786928990d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
