"""Add thumbnail_path to Job model

Revision ID: f834fba1bf14
Revises: 
Create Date: 2025-05-08 16:13:07.822520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f834fba1bf14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_job')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')

    op.create_table('print_job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('discipline', sa.VARCHAR(), nullable=True),
    sa.Column('course', sa.VARCHAR(), nullable=True),
    sa.Column('print_method', sa.VARCHAR(), nullable=True),
    sa.Column('print_color', sa.VARCHAR(), nullable=True),
    sa.Column('scaled', sa.VARCHAR(), nullable=True),
    sa.Column('simplified', sa.VARCHAR(), nullable=True),
    sa.Column('overhangs', sa.VARCHAR(), nullable=True),
    sa.Column('file_type', sa.VARCHAR(), nullable=True),
    sa.Column('minimum_ok', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('time', sa.FLOAT(), nullable=True),
    sa.Column('rejection_reasons', sa.VARCHAR(), nullable=True),
    sa.Column('submitted', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    # ### end Alembic commands ###
